### ISSUE TITLE
Update README and add screenshots

### ISSUE THREAD

**Issue by dmahajan980** [dmahajan980/node-weather-app#1]
The curreny README is an overview of what the project is. But in general, more details can be added so that the users can get more insight without navigating across the codebase (extended description, labels, screenshots).

**Comment by roninJosue** [comment]
Hello, can i do this issue for Hacktoberfest?

**Comment by dmahajan980** [comment]
Hi @roninJosue,

Yes, this issue is for Hacktoberfest. You can pick it up if you're interested!

**Comment by roninJosue** [comment]
Ok thanks

**Comment by Kajal18** [comment]
Hey, I would like to contribute to your project

**Comment by dmahajan980** [comment]
Hi @Kajal18, thanks for your interest in contributing to this project. This issue already has a pull request under review. But I'll suggest you to try the web app, play with it, and then feel free to open a new issue ticket in the repository for any issues you find. I'll mark that as a Hacktoberfest issue :)

**Comment by Kajal18** [comment]
okay, thank you

**Comment by dmahajan980** [comment]
Closing this with the pull request sent by @roninJosue
